import { ReactNode } from 'react';
import Layout from '@/components/Layout';

export const metadata = {
  title: '売上速報&自空マップ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <Layout>
      {children}
    </Layout>
  );
}