import '@/styles/global.css';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import { MobileProvider } from '@/contexts/MobileContext';

export const metadata = {
  title: '売上速報&自空マップ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <MobileProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </MobileProvider>
      </body>
    </html>
  );
}