//店舗データ
export const stores_info_sequential = () => {
   return [
        {
            id: "1",
            BaseNo: "001",
            BaseName: "店舗aaaaaaaaaaaaaa1",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー1,オーナー1,オーナー1,オーナー1,オーナー1,オーナー1",
        },
        {
            id: "2",
            BaseNo: "002",
            BaseName: "店舗gsdfgdsg2",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー2,オーナー1,オーナー1fgsdfgsdfgd",
        },
        {
            id: "3",
            BaseNo: "003",
            BaseName: "店舗3",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー3",
        },
        {
            id: "4",
            BaseNo: "004",
            BaseName: "店舗4",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー4",
        },
        {
            id: "5",
            BaseNo: "005",
            BaseName: "店舗5",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー5",
        },
        {
            id: "6",
            BaseNo: "006",
            BaseName: "店舗6",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー6",
        },
        {
            id: "7",
            BaseNo: "007",
            BaseName: "店舗7",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー7",
        },
        {
            id: "8",
            BaseNo: "008",
            BaseName: "店舗8",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー8",
        },
        {
            id: "9",
            BaseNo: "009",
            BaseName: "店舗9",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー9",
        },
        {
            id: "10",
            BaseNo: "010",
            BaseName: "店舗10",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー10",
        },
        {
            id: "11",
            BaseNo: "011",
            BaseName: "店舗11",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー11",
        },
        {
            id: "12",
            BaseNo: "012",
            BaseName: "店舗12",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー12",
        },
        {
            id: "13",
            BaseNo: "013",
            BaseName: "店舗13",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー13",
        },
        {
            id: "14",
            BaseNo: "014",
            BaseName: "店舗14",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー14",
        },
        {
            id: "15",
            BaseNo: "015",
            BaseName: "店舗15",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー15",
        },
        {
            id: "16",
            BaseNo: "016",
            BaseName: "店舗16",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー16",
        },
        {
            id: "17",
            BaseNo: "001",
            BaseName: "店舗1",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー1",
        },
        {
            id: "18",
            BaseNo: "002",
            BaseName: "店舗2",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー2",
        },
        {
            id: "19",
            BaseNo: "003",
            BaseName: "店舗3",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー3",
        },
        {
            id: "20",
            BaseNo: "004",
            BaseName: "店舗4",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー4",
        },
        {
            id: "21",
            BaseNo: "005",
            BaseName: "店舗5",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー5",
        },
        {
            id: "22",
            BaseNo: "006",
            BaseName: "店舗6",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー6",
        },
        {
            id: "23",
            BaseNo: "007",
            BaseName: "店舗7",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー7",
        },
        {
            id: "24",
            BaseNo: "008",
            BaseName: "店舗8",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー8",
        },
        {
            id: "25",
            BaseNo: "009",
            BaseName: "店舗9",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー9",
        },
        {
            id: "26",
            BaseNo: "010",
            BaseName: "店舗10",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー10",
        },
        {
            id: "27",
            BaseNo: "011",
            BaseName: "店舗11",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー11",
        },
        {
            id: "28",
            BaseNo: "012",
            BaseName: "店舗12",
            Class: "FC",
            Area: "郊外",
            Owner: "オーナー12",
        },
        {
            id: "29",
            BaseNo: "013",
            BaseName: "店舗13",
            Class: "FC",
            Area: "駅前",
            Owner: "オーナー13",
        },
        {
            id: "30",
            BaseNo: "014",
            BaseName: "店舗14",
            Class: "直営",
            Area: "駅前",
            Owner: "オーナー14",
        },
        {
            id: "31",
            BaseNo: "015",
            BaseName: "店舗15",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー15",
        },
        {
            id: "32",
            BaseNo: "016",
            BaseName: "店舗16",
            Class: "直営",
            Area: "郊外",
            Owner: "オーナー16",
        },
    ];
};